import 'dart:math';

class Country {
  const Country({
    required this.id,
    required this.name,
    required this.flag,
    required this.dialCode,
    this.minLength = 5,
    this.maxLength = 13,
  });
  final String id;
  final String name;
  final String flag;
  final String dialCode;
  final int minLength;
  final int maxLength;
}

class Countries {
  static const List<Country> all = [
    Country(id: 'GB', name: 'United Kingdom', flag: '🇬🇧', dialCode: '+44', minLength: 10, maxLength: 11),
    Country(id: 'ES', name: 'Spain', flag: '🇪🇸', dialCode: '+34', minLength: 9, maxLength: 9),
    Country(id: 'FR', name: 'France', flag: '🇫🇷', dialCode: '+33', minLength: 9, maxLength: 9),
    Country(id: 'DE', name: 'Germany', flag: '🇩🇪', dialCode: '+49', minLength: 10, maxLength: 11),
    Country(id: 'RU', name: 'Russia', flag: '🇷🇺', dialCode: '+7', minLength: 10, maxLength: 10),
    Country(id: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', dialCode: '+966', minLength: 9, maxLength: 9),
    Country(id: 'JP', name: 'Japan', flag: '🇯🇵', dialCode: '+81', minLength: 10, maxLength: 10),
    Country(id: 'KR', name: 'South Korea', flag: '🇰🇷', dialCode: '+82', minLength: 10, maxLength: 11),
    Country(id: 'CN', name: 'China', flag: '🇨🇳', dialCode: '+86', minLength: 11, maxLength: 11),
    Country(id: 'AF', name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93', minLength: 9, maxLength: 9),
    Country(id: 'AL', name: 'Albania', flag: '🇦🇱', dialCode: '+355', minLength: 9, maxLength: 9),
    Country(id: 'DZ', name: 'Algeria', flag: '🇩🇿', dialCode: '+213', minLength: 9, maxLength: 9),
    Country(id: 'AD', name: 'Andorra', flag: '🇦🇩', dialCode: '+376', minLength: 6, maxLength: 9),
    Country(id: 'AO', name: 'Angola', flag: '🇦🇴', dialCode: '+244', minLength: 9, maxLength: 9),
    Country(id: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', dialCode: '+1268', minLength: 10, maxLength: 10),
    Country(id: 'AR', name: 'Argentina', flag: '🇦🇷', dialCode: '+54', minLength: 10, maxLength: 10),
    Country(id: 'AM', name: 'Armenia', flag: '🇦🇲', dialCode: '+374', minLength: 8, maxLength: 8),
    Country(id: 'AU', name: 'Australia', flag: '🇦🇺', dialCode: '+61', minLength: 9, maxLength: 9),
    Country(id: 'AT', name: 'Austria', flag: '🇦🇹', dialCode: '+43', minLength: 10),
    Country(id: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263', minLength: 9, maxLength: 9),
    Country(id: 'PS', name: 'Palestine', flag: '🇵🇸', dialCode: '+970', minLength: 9, maxLength: 9),
    Country(id: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', dialCode: '+994', minLength: 9, maxLength: 9),
    Country(id: 'BS', name: 'Bahamas', flag: '🇧🇸', dialCode: '+1242', minLength: 10, maxLength: 10),
    Country(id: 'BH', name: 'Bahrain', flag: '🇧🇭', dialCode: '+973', minLength: 8, maxLength: 8),
    Country(id: 'BD', name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880', minLength: 10, maxLength: 10),
    Country(id: 'BB', name: 'Barbados', flag: '🇧🇧', dialCode: '+1246', minLength: 10, maxLength: 10),
    Country(id: 'BY', name: 'Belarus', flag: '🇧🇾', dialCode: '+375', minLength: 9, maxLength: 9),
    Country(id: 'BE', name: 'Belgium', flag: '🇧🇪', dialCode: '+32', minLength: 9, maxLength: 9),
    Country(id: 'BZ', name: 'Belize', flag: '🇧🇿', dialCode: '+501', minLength: 7, maxLength: 7),
    Country(id: 'BJ', name: 'Benin', flag: '🇧🇯', dialCode: '+229', minLength: 8, maxLength: 8),
    Country(id: 'BT', name: 'Bhutan', flag: '🇧🇹', dialCode: '+975', minLength: 8, maxLength: 8),
    Country(id: 'BO', name: 'Bolivia', flag: '🇧🇴', dialCode: '+591', minLength: 8, maxLength: 8),
    Country(id: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', dialCode: '+387', minLength: 8, maxLength: 8),
    Country(id: 'BW', name: 'Botswana', flag: '🇧🇼', dialCode: '+267', minLength: 8, maxLength: 8),
    Country(id: 'BR', name: 'Brazil', flag: '🇧🇷', dialCode: '+55', minLength: 10, maxLength: 11),
    Country(id: 'BN', name: 'Brunei', flag: '🇧🇳', dialCode: '+673', minLength: 7, maxLength: 7),
    Country(id: 'BG', name: 'Bulgaria', flag: '🇧🇬', dialCode: '+359', minLength: 9, maxLength: 9),
    Country(id: 'BF', name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226', minLength: 8, maxLength: 8),
    Country(id: 'BI', name: 'Burundi', flag: '🇧🇮', dialCode: '+257', minLength: 8, maxLength: 8),
    Country(id: 'CV', name: 'Cabo Verde', flag: '🇨🇻', dialCode: '+238', minLength: 7, maxLength: 7),
    Country(id: 'KH', name: 'Cambodia', flag: '🇰🇭', dialCode: '+855', minLength: 9, maxLength: 9),
    Country(id: 'CM', name: 'Cameroon', flag: '🇨🇲', dialCode: '+237', minLength: 9, maxLength: 9),
    Country(id: 'CA', name: 'Canada', flag: '🇨🇦', dialCode: '+1', minLength: 10, maxLength: 10),
    Country(id: 'CF', name: 'Central African Republic', flag: '🇨🇫', dialCode: '+236', minLength: 8, maxLength: 8),
    Country(id: 'TD', name: 'Chad', flag: '🇹🇩', dialCode: '+235', minLength: 8, maxLength: 8),
    Country(id: 'CL', name: 'Chile', flag: '🇨🇱', dialCode: '+56', minLength: 9, maxLength: 9),
    Country(id: 'CO', name: 'Colombia', flag: '🇨🇴', dialCode: '+57', minLength: 10, maxLength: 10),
    Country(id: 'KM', name: 'Comoros', flag: '🇰🇲', dialCode: '+269', minLength: 7, maxLength: 7),
    Country(
        id: 'CD',
        name: 'Congo, Democratic Republic of the',
        flag: '🇨🇩',
        dialCode: '+243',
        minLength: 9,
        maxLength: 9),
    Country(id: 'CG', name: 'Congo, Republic of the', flag: '🇨🇬', dialCode: '+242', minLength: 9, maxLength: 9),
    Country(id: 'CR', name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506', minLength: 8, maxLength: 8),
    Country(id: 'HR', name: 'Croatia', flag: '🇭🇷', dialCode: '+385', minLength: 9, maxLength: 9),
    Country(id: 'CU', name: 'Cuba', flag: '🇨🇺', dialCode: '+53', minLength: 8, maxLength: 8),
    Country(id: 'CY', name: 'Cyprus', flag: '🇨🇾', dialCode: '+357', minLength: 8, maxLength: 8),
    Country(id: 'CZ', name: 'Czech Republic', flag: '🇨🇿', dialCode: '+420', minLength: 9, maxLength: 9),
    Country(id: 'DK', name: 'Denmark', flag: '🇩🇰', dialCode: '+45', minLength: 8, maxLength: 8),
    Country(id: 'DJ', name: 'Djibouti', flag: '🇩🇯', dialCode: '+253', minLength: 8, maxLength: 8),
    Country(id: 'DM', name: 'Dominica', flag: '🇩🇲', dialCode: '+1767', minLength: 10, maxLength: 10),
    Country(id: 'DO', name: 'Dominican Republic', flag: '🇩🇴', dialCode: '+1849', minLength: 10, maxLength: 10),
    Country(id: 'EC', name: 'Ecuador', flag: '🇪🇨', dialCode: '+593', minLength: 9, maxLength: 9),
    Country(id: 'EG', name: 'Egypt', flag: '🇪🇬', dialCode: '+20', minLength: 10, maxLength: 10),
    Country(id: 'SV', name: 'El Salvador', flag: '🇸🇻', dialCode: '+503', minLength: 8, maxLength: 8),
    Country(id: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', dialCode: '+240', minLength: 9, maxLength: 9),
    Country(id: 'ER', name: 'Eritrea', flag: '🇪🇷', dialCode: '+291', minLength: 7, maxLength: 7),
    Country(id: 'EE', name: 'Estonia', flag: '🇪🇪', dialCode: '+372', minLength: 8, maxLength: 8),
    Country(id: 'SZ', name: 'Eswatini', flag: '🇸🇿', dialCode: '+268', minLength: 8, maxLength: 8),
    Country(id: 'ET', name: 'Ethiopia', flag: '🇪🇹', dialCode: '+251', minLength: 9, maxLength: 9),
    Country(id: 'FJ', name: 'Fiji', flag: '🇫🇯', dialCode: '+679', minLength: 7, maxLength: 7),
    Country(id: 'FI', name: 'Finland', flag: '🇫🇮', dialCode: '+358', minLength: 9, maxLength: 10),
    Country(id: 'GA', name: 'Gabon', flag: '🇬🇦', dialCode: '+241', minLength: 8, maxLength: 8),
    Country(id: 'GM', name: 'Gambia', flag: '🇬🇲', dialCode: '+220', minLength: 7, maxLength: 7),
    Country(id: 'GE', name: 'Georgia', flag: '🇬🇪', dialCode: '+995', minLength: 9, maxLength: 9),
    Country(id: 'GH', name: 'Ghana', flag: '🇬🇭', dialCode: '+233', minLength: 9, maxLength: 9),
    Country(id: 'GR', name: 'Greece', flag: '🇬🇷', dialCode: '+30', minLength: 10, maxLength: 10),
    Country(id: 'GD', name: 'Grenada', flag: '🇬🇩', dialCode: '+1473', minLength: 10, maxLength: 10),
    Country(id: 'GT', name: 'Guatemala', flag: '🇬🇹', dialCode: '+502', minLength: 8, maxLength: 8),
    Country(id: 'GN', name: 'Guinea', flag: '🇬🇳', dialCode: '+224', minLength: 9, maxLength: 9),
    Country(id: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', dialCode: '+245', minLength: 7, maxLength: 7),
    Country(id: 'GY', name: 'Guyana', flag: '🇬🇾', dialCode: '+592', minLength: 7, maxLength: 7),
    Country(id: 'HT', name: 'Haiti', flag: '🇭🇹', dialCode: '+509', minLength: 8, maxLength: 8),
    Country(id: 'HN', name: 'Honduras', flag: '🇭🇳', dialCode: '+504', minLength: 8, maxLength: 8),
    Country(id: 'HU', name: 'Hungary', flag: '🇭🇺', dialCode: '+36', minLength: 9, maxLength: 9),
    Country(id: 'IS', name: 'Iceland', flag: '🇮🇸', dialCode: '+354', minLength: 7, maxLength: 9),
    Country(id: 'IN', name: 'India', flag: '🇮🇳', dialCode: '+91', minLength: 10, maxLength: 10),
    Country(id: 'ID', name: 'Indonesia', flag: '🇮🇩', dialCode: '+62', minLength: 10),
    Country(id: 'IR', name: 'Iran', flag: '🇮🇷', dialCode: '+98', minLength: 10, maxLength: 10),
    Country(id: 'IQ', name: 'Iraq', flag: '🇮🇶', dialCode: '+964', minLength: 10, maxLength: 10),
    Country(id: 'IE', name: 'Ireland', flag: '🇮🇪', dialCode: '+353', minLength: 9, maxLength: 9),
    Country(id: 'IL', name: 'Israel', flag: '🇮🇱', dialCode: '+972', minLength: 9, maxLength: 9),
    Country(id: 'IT', name: 'Italy', flag: '🇮🇹', dialCode: '+39', minLength: 10, maxLength: 10),
    Country(id: 'CI', name: 'Ivory Coast', flag: '🇨🇮', dialCode: '+225', minLength: 8, maxLength: 8),
    Country(id: 'JM', name: 'Jamaica', flag: '🇯🇲', dialCode: '+1876', minLength: 10, maxLength: 10),
    Country(id: 'JO', name: 'Jordan', flag: '🇯🇴', dialCode: '+962', minLength: 9, maxLength: 9),
    Country(id: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7', minLength: 10, maxLength: 10),
    Country(id: 'KE', name: 'Kenya', flag: '🇰🇪', dialCode: '+254', minLength: 9, maxLength: 9),
    Country(id: 'KI', name: 'Kiribati', flag: '🇰🇮', dialCode: '+686', maxLength: 5),
    Country(id: 'KP', name: 'North Korea', flag: '🇰🇵', dialCode: '+850', minLength: 10, maxLength: 10),
    Country(id: 'XK', name: 'Kosovo', flag: '🇽🇰', dialCode: '+383', minLength: 8, maxLength: 9),
    Country(id: 'KW', name: 'Kuwait', flag: '🇰🇼', dialCode: '+965', minLength: 8, maxLength: 8),
    Country(id: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', dialCode: '+996', minLength: 9, maxLength: 9),
    Country(id: 'LA', name: 'Laos', flag: '🇱🇦', dialCode: '+856', minLength: 9, maxLength: 9),
    Country(id: 'LV', name: 'Latvia', flag: '🇱🇻', dialCode: '+371', minLength: 8, maxLength: 8),
    Country(id: 'LB', name: 'Lebanon', flag: '🇱🇧', dialCode: '+961', minLength: 7, maxLength: 8),
    Country(id: 'LS', name: 'Lesotho', flag: '🇱🇸', dialCode: '+266', minLength: 8, maxLength: 8),
    Country(id: 'LR', name: 'Liberia', flag: '🇱🇷', dialCode: '+231', minLength: 7, maxLength: 7),
    Country(id: 'LY', name: 'Libya', flag: '🇱🇾', dialCode: '+218', minLength: 9, maxLength: 9),
    Country(id: 'LI', name: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423', minLength: 7, maxLength: 7),
    Country(id: 'LT', name: 'Lithuania', flag: '🇱🇹', dialCode: '+370', minLength: 8, maxLength: 8),
    Country(id: 'LU', name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352', minLength: 9, maxLength: 9),
    Country(id: 'MG', name: 'Madagascar', flag: '🇲🇬', dialCode: '+261', minLength: 9, maxLength: 9),
    Country(id: 'MW', name: 'Malawi', flag: '🇲🇼', dialCode: '+265', minLength: 9, maxLength: 9),
    Country(id: 'MY', name: 'Malaysia', flag: '🇲🇾', dialCode: '+60', minLength: 9, maxLength: 10),
    Country(id: 'MV', name: 'Maldives', flag: '🇲🇻', dialCode: '+960', minLength: 7, maxLength: 7),
    Country(id: 'ML', name: 'Mali', flag: '🇲🇱', dialCode: '+223', minLength: 8, maxLength: 8),
    Country(id: 'MT', name: 'Malta', flag: '🇲🇹', dialCode: '+356', minLength: 8, maxLength: 8),
    Country(id: 'MH', name: 'Marshall Islands', flag: '🇲🇭', dialCode: '+692', minLength: 7, maxLength: 7),
    Country(id: 'MR', name: 'Mauritania', flag: '🇲🇷', dialCode: '+222', minLength: 9, maxLength: 9),
    Country(id: 'MU', name: 'Mauritius', flag: '🇲🇺', dialCode: '+230', minLength: 7, maxLength: 8),
    Country(id: 'MX', name: 'Mexico', flag: '🇲🇽', dialCode: '+52', minLength: 10, maxLength: 10),
    Country(id: 'FM', name: 'Micronesia', flag: '🇫🇲', dialCode: '+691', minLength: 7, maxLength: 7),
    Country(id: 'MD', name: 'Moldova', flag: '🇲🇩', dialCode: '+373', minLength: 8, maxLength: 8),
    Country(id: 'MC', name: 'Monaco', flag: '🇲🇨', dialCode: '+377', minLength: 8, maxLength: 8),
    Country(id: 'MN', name: 'Mongolia', flag: '🇲🇳', dialCode: '+976', minLength: 8, maxLength: 8),
    Country(id: 'ME', name: 'Montenegro', flag: '🇲🇪', dialCode: '+382', minLength: 8, maxLength: 9),
    Country(id: 'MA', name: 'Morocco', flag: '🇲🇦', dialCode: '+212', minLength: 9, maxLength: 9),
    Country(id: 'MZ', name: 'Mozambique', flag: '🇲🇿', dialCode: '+258', minLength: 9, maxLength: 9),
    Country(id: 'MM', name: 'Myanmar (Burma)', flag: '🇲🇲', dialCode: '+95', minLength: 9, maxLength: 9),
    Country(id: 'NA', name: 'Namibia', flag: '🇳🇦', dialCode: '+264', minLength: 9, maxLength: 9),
    Country(id: 'NR', name: 'Nauru', flag: '🇳🇷', dialCode: '+674', minLength: 7, maxLength: 7),
    Country(id: 'NP', name: 'Nepal', flag: '🇳🇵', dialCode: '+977', minLength: 10, maxLength: 10),
    Country(id: 'NL', name: 'Netherlands', flag: '🇳🇱', dialCode: '+31', minLength: 9, maxLength: 9),
    Country(id: 'NZ', name: 'New Zealand', flag: '🇳🇿', dialCode: '+64', minLength: 9, maxLength: 10),
    Country(id: 'NI', name: 'Nicaragua', flag: '🇳🇮', dialCode: '+505', minLength: 8, maxLength: 8),
    Country(id: 'NE', name: 'Niger', flag: '🇳🇪', dialCode: '+227', minLength: 8, maxLength: 8),
    Country(id: 'NG', name: 'Nigeria', flag: '🇳🇬', dialCode: '+234', minLength: 10, maxLength: 10),
    Country(id: 'MK', name: 'North Macedonia', flag: '🇲🇰', dialCode: '+389', minLength: 8, maxLength: 8),
    Country(id: 'NO', name: 'Norway', flag: '🇳🇴', dialCode: '+47', minLength: 8, maxLength: 8),
    Country(id: 'OM', name: 'Oman', flag: '🇴🇲', dialCode: '+968', minLength: 8, maxLength: 8),
    Country(id: 'PK', name: 'Pakistan', flag: '🇵🇰', dialCode: '+92', minLength: 10, maxLength: 10),
    Country(id: 'PW', name: 'Palau', flag: '🇵🇼', dialCode: '+680', minLength: 7, maxLength: 7),
    Country(id: 'PA', name: 'Panama', flag: '🇵🇦', dialCode: '+507', minLength: 8, maxLength: 8),
    Country(id: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', dialCode: '+675', minLength: 8, maxLength: 8),
    Country(id: 'PY', name: 'Paraguay', flag: '🇵🇾', dialCode: '+595', minLength: 9, maxLength: 9),
    Country(id: 'PE', name: 'Peru', flag: '🇵🇪', dialCode: '+51', minLength: 9, maxLength: 9),
    Country(id: 'PH', name: 'Philippines', flag: '🇵🇭', dialCode: '+63', minLength: 10, maxLength: 10),
    Country(id: 'PL', name: 'Poland', flag: '🇵🇱', dialCode: '+48', minLength: 9, maxLength: 9),
    Country(id: 'PT', name: 'Portugal', flag: '🇵🇹', dialCode: '+351', minLength: 9, maxLength: 9),
    Country(id: 'QA', name: 'Qatar', flag: '🇶🇦', dialCode: '+974', minLength: 8, maxLength: 8),
    Country(id: 'RO', name: 'Romania', flag: '🇷🇴', dialCode: '+40', minLength: 9, maxLength: 9),
    Country(id: 'RW', name: 'Rwanda', flag: '🇷🇼', dialCode: '+250', minLength: 9, maxLength: 9),
    Country(id: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', dialCode: '+1869', minLength: 10, maxLength: 10),
    Country(id: 'LC', name: 'Saint Lucia', flag: '🇱🇨', dialCode: '+1758', minLength: 10, maxLength: 10),
    Country(
        id: 'VC',
        name: 'Saint Vincent and the Grenadines',
        flag: '🇻🇨',
        dialCode: '+1784',
        minLength: 10,
        maxLength: 10),
    Country(id: 'WS', name: 'Samoa', flag: '🇼🇸', dialCode: '+685', maxLength: 7),
    Country(id: 'SM', name: 'San Marino', flag: '🇸🇲', dialCode: '+378', minLength: 8, maxLength: 8),
    Country(id: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', dialCode: '+239', minLength: 7, maxLength: 7),
    Country(id: 'SN', name: 'Senegal', flag: '🇸🇳', dialCode: '+221', minLength: 9, maxLength: 9),
    Country(id: 'RS', name: 'Serbia', flag: '🇷🇸', dialCode: '+381', minLength: 8, maxLength: 9),
    Country(id: 'SC', name: 'Seychelles', flag: '🇸🇨', dialCode: '+248', minLength: 7, maxLength: 7),
    Country(id: 'SL', name: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232', minLength: 8, maxLength: 8),
    Country(id: 'SG', name: 'Singapore', flag: '🇸🇬', dialCode: '+65', minLength: 8, maxLength: 8),
    Country(id: 'SK', name: 'Slovakia', flag: '🇸🇰', dialCode: '+421', minLength: 9, maxLength: 9),
    Country(id: 'SI', name: 'Slovenia', flag: '🇸🇮', dialCode: '+386', minLength: 8, maxLength: 8),
    Country(id: 'SB', name: 'Solomon Islands', flag: '🇸🇧', dialCode: '+677', minLength: 7, maxLength: 7),
    Country(id: 'SO', name: 'Somalia', flag: '🇸🇴', dialCode: '+252', minLength: 8, maxLength: 9),
    Country(id: 'ZA', name: 'South Africa', flag: '🇿🇦', dialCode: '+27', minLength: 9, maxLength: 9),
    Country(id: 'SS', name: 'South Sudan', flag: '🇸🇸', dialCode: '+211', minLength: 9, maxLength: 9),
    Country(id: 'LK', name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94', minLength: 9, maxLength: 9),
    Country(id: 'SD', name: 'Sudan', flag: '🇸🇩', dialCode: '+249', minLength: 9, maxLength: 9),
    Country(id: 'SR', name: 'Suriname', flag: '🇸🇷', dialCode: '+597', minLength: 7, maxLength: 7),
    Country(id: 'SE', name: 'Sweden', flag: '🇸🇪', dialCode: '+46', minLength: 9, maxLength: 10),
    Country(id: 'CH', name: 'Switzerland', flag: '🇨🇭', dialCode: '+41', minLength: 9, maxLength: 10),
    Country(id: 'SY', name: 'Syria', flag: '🇸🇾', dialCode: '+963', minLength: 9, maxLength: 10),
    Country(id: 'TW', name: 'Taiwan', flag: '🇹🇼', dialCode: '+886', minLength: 9, maxLength: 9),
    Country(id: 'TJ', name: 'Tajikistan', flag: '🇹🇯', dialCode: '+992', minLength: 9, maxLength: 9),
    Country(id: 'TZ', name: 'Tanzania', flag: '🇹🇿', dialCode: '+255', minLength: 9, maxLength: 9),
    Country(id: 'TH', name: 'Thailand', flag: '🇹🇭', dialCode: '+66', minLength: 9, maxLength: 10),
    Country(id: 'TG', name: 'Togo', flag: '🇹🇬', dialCode: '+228', minLength: 8, maxLength: 8),
    Country(id: 'TO', name: 'Tonga', flag: '🇹🇴', dialCode: '+676', minLength: 7, maxLength: 7),
    Country(id: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', dialCode: '+1868', minLength: 10, maxLength: 10),
    Country(id: 'TN', name: 'Tunisia', flag: '🇹🇳', dialCode: '+216', minLength: 8, maxLength: 8),
    Country(id: 'TR', name: 'Turkey', flag: '🇹🇷', dialCode: '+90', minLength: 10, maxLength: 10),
    Country(id: 'TM', name: 'Turkmenistan', flag: '🇹🇲', dialCode: '+993', minLength: 8, maxLength: 8),
    Country(id: 'TV', name: 'Tuvalu', flag: '🇹🇻', dialCode: '+688', maxLength: 6),
    Country(id: 'UG', name: 'Uganda', flag: '🇺🇬', dialCode: '+256', minLength: 9, maxLength: 9),
    Country(id: 'UA', name: 'Ukraine', flag: '🇺🇦', dialCode: '+380', minLength: 9, maxLength: 9),
    Country(id: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', dialCode: '+971', minLength: 9, maxLength: 9),
    Country(id: 'UY', name: 'Uruguay', flag: '🇺🇾', dialCode: '+598', minLength: 8, maxLength: 8),
    Country(id: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', dialCode: '+998', minLength: 9, maxLength: 9),
    Country(id: 'VU', name: 'Vanuatu', flag: '🇻🇺', dialCode: '+678', minLength: 7, maxLength: 7),
    Country(id: 'VA', name: 'Vatican City', flag: '🇻🇦', dialCode: '+379', minLength: 10, maxLength: 10),
    Country(id: 'VE', name: 'Venezuela', flag: '🇻🇪', dialCode: '+58', minLength: 10, maxLength: 10),
    Country(id: 'VN', name: 'Vietnam', flag: '🇻🇳', dialCode: '+84', minLength: 9, maxLength: 10),
    Country(id: 'TL', name: 'East Timor (Timor-Leste)', flag: '🇹🇱', dialCode: '+670', minLength: 7, maxLength: 8),
    Country(id: 'US', name: 'United States', flag: '🇺🇸', dialCode: '+1', minLength: 10, maxLength: 10),
    Country(id: 'YE', name: 'Yemen', flag: '🇾🇪', dialCode: '+967', minLength: 9, maxLength: 9),
    Country(id: 'ZM', name: 'Zambia', flag: '🇿🇲', dialCode: '+260', minLength: 9, maxLength: 9),
  ];

  static int get smallestMinLength => all.map((country) => country.minLength).reduce(min);

  static int get largestMaxLength => all.map((country) => country.maxLength).reduce(max);

  static Country getByCode(String id) => all.firstWhere(
        (country) => country.id == id,
        orElse: () => all.first,
      );

  static List<Country> get allSortedByDialCode => List<Country>.from(all)
    ..sort((a, b) {
      final aCode = int.parse(a.dialCode.substring(1));
      final bCode = int.parse(b.dialCode.substring(1));
      return aCode.compareTo(bCode);
    });
}
